engines:
  duplication:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  markdownlint:
    enabled: true
    config:
      line_length: 120
  shellcheck:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.md"
