engines:
  duplication:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  markdownlint:
    enabled: true
    config:
      punctutation: '.,;:!'
    checks:
      MD013:
        enabled: false
      MD036:
        enabled: false
  shellcheck:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.md"
